### ISSUE TITLE
Add Student ID as a unlock tag

### ISSUE THREAD

**Issue by ramandeepkau** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#103]
As a developer, I want to add my student ID to the RFID lock/unlock system code and test it, so that I can ensure the system correctly recognizes and processes my student ID for unlocking and locking actions.

**Comment by SamanthaCra** [comment]
Closing as this is a user story. Please refer to the wiki for how to write issues correctly. https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/wiki
