### ISSUE TITLE
Putting everything together 

### ISSUE THREAD

**Issue by ramandeepkau** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#118]
Assemble the Cabinet and every bit of it to make it a real Arcade machine.  it needed all the hands and working together to contribute to the technical bits of the paper.

**Comment by ramandeepkau** [comment]
At last, we can post a video/pictures of the final Arcade machine.

**Comment by SamanthaCra** [comment]
This is already an issue.  Assemble the cabinet #70 Please update the existing issue.
