### ISSUE TITLE
Game accessibility 

### ISSUE THREAD

**Issue by TomMc608** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#13]
As a user/owner, I want to be able to control what games are accessible to different age groups.

**Comment by ramandeepkau** [comment]
Already exists

**Comment by ramandeepkau** [comment]
Closing as its a duplicate issue

**Comment by SamanthaCra** [comment]
@TomMc608 does this need to be converted into a milestone (userstory) and a seperate issue created?

**Comment by SamanthaCra** [comment]
Converted.
