### ISSUE TITLE
LED Marquee

### ISSUE THREAD

**Issue by OP-ReubenK** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#17]
Create a matrix LED marquee to display text

**Comment by kierenblack** [comment]
I have emailed @vmalkin with some parts to get this started

**Comment by kierenblack** [comment]
The hardware for the LED's arrived. Waiting on a backboard to attach the LED's too.

**Comment by kierenblack** [comment]
Got a demo text working
![20240328_141611](https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/assets/4483969/41d65dc5-a205-4d2c-bfe1-064890db64c4)

https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/assets/4483969/768b7a75-14b0-427a-99ad-020444fdf316

**Comment by kierenblack** [comment]
We have gone with an 8 X 45 LED matrix. This is due to size constraints of the cabinet which is being designed around the size of the screen
