### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by ramandeepkau** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#22]
As a player, I want the arcade cabinet to have a sleek and attractive design with easy accessibility to all features, enhancing my overall gaming experience and interaction with the cabinet.

**Comment by vmalkin** [comment]
this is something that needs to be fed back to Grayson ASAP

**Comment by SamanthaCra** [comment]
Closing as this is a user story.
