### ISSUE TITLE
Verify Existing game hardware

### ISSUE THREAD

**Issue by vmalkin** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#25]
@SamanthaCra @fuzzyers 

Can you pull the existing PC out of the games cabinet and set it up in the hardware troom. We need to verify that it will support the kind of games that Grayson's team is writing

**Comment by SamanthaCra** [comment]
PC boots - exterior fans and GPU fans spin.

**Comment by SamanthaCra** [comment]
AMD-6100 Six Core Processor
16GB Ram
Windows 10
Some sort of NVIDIA GPU

**Comment by SamanthaCra** [comment]
CPU - https://www.amd.com/en/support/cpu/amd-fx-series-processors/amd-fx-6-core-black-edition-processors/fx-6100

**Comment by SamanthaCra** [comment]
Still testing the software capabilities of the existing PC.

**Comment by fuzzyers** [comment]
The computer has a slow ethernet connection speed and no wifi
When running our test game it took about a minute to load into the level

**Comment by SamanthaCra** [comment]
We have recieved a new PC from Rob and will be using that for this project.
