### ISSUE TITLE
Creating a 3D Model 

### ISSUE THREAD

**Issue by SamanthaCra** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#28]
Grayson has requested a 3D model for the conceptual design of the cabinet.

**Comment by vmalkin** [comment]
Grayson has requested this - why was this canned?

**Comment by SamanthaCra** [comment]
![image](https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/assets/104808327/2fa3d657-568b-4f6a-b6e9-a94e5d40fc42)
First rough shape made. Will be starting a new iteration after discussion with Grayson.

**Comment by SamanthaCra** [comment]
@fuzzyers Has taken over this task.

**Comment by fuzzyers** [comment]
![image](https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/assets/104363831/d9311408-2a28-422c-a4fa-50589ba5b3a3)

Cabinet design

**Comment by fuzzyers** [comment]
[Arcade Machine v7 Drawing v5.pdf](https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/files/14940083/Arcade.Machine.v7.Drawing.v5.pdf)

Finished Drawings for the arcade

**Comment by SamanthaCra** [comment]
Model has been seen by team and client and approved.
