### ISSUE TITLE
Frontend 

### ISSUE THREAD

**Issue by fuzzyers** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#30]
https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/wiki/Frontend-Research

Research how to put together a frontend that will be intuitive and able to launch selected games to be run on the arcade machine

**Comment by SamanthaCra** [comment]
@fuzzyers can this be closed now?

**Comment by fuzzyers** [comment]
https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/wiki/Frontend-Research
