### ISSUE TITLE
RFID token 

### ISSUE THREAD

**Issue by ramandeepkau** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#31]
As an arcade gamer, I want to use an RFID token to access games, track my progress, and manage credits, ensuring a seamless and personalized gaming experience.

**Comment by ramandeepkau** [comment]
The working code can be found here: https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/pull/45 . The hardware is in the hardware room. We can modify it according tot he client's needs .

**Comment by OP-ReubenK** [comment]
this is related to issue #47
