### ISSUE TITLE
Arcade UI

### ISSUE THREAD

**Issue by OP-ReubenK** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#33]
Creating the actual user experience that will be displayed on the arcade machine.

**Comment by OP-ReubenK** [comment]
Researching and working with Electron-React

**Comment by OP-ReubenK** [comment]
![027676f0-cfa9-41ca-a03d-846a1f3fc00f](https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/assets/83677423/850ee8b1-c323-42af-9d76-1fffdd1b00ac)

**Comment by OP-ReubenK** [comment]
https://stackoverflow.com/questions/45715989/run-a-non-electron-executable-inside-electron-window

https://stackoverflow.com/questions/63697768/application-launcher-using-an-electron-js-app

https://www.electronjs.org/de/docs/latest/tutorial/ipc

**Comment by SamanthaCra** [comment]
![image](https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/assets/104808327/115c1987-3cb7-4d3f-bd0d-8dc5ced5ad66)
Uploaded your work here for evidence :)
