### ISSUE TITLE
Clean up the issues and convert user stories to milestones

### ISSUE THREAD

**Issue by SamanthaCra** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#34]
Vaughn has instructed that we convert any non-issue user stories to milestones and link them to relevant issues instead.

**Comment by ramandeepkau** [comment]
The issues are now linked with milestones. Can be found here: https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/milestones

**Comment by SamanthaCra** [comment]
This is ongoing work.
