### ISSUE TITLE
game execution

### ISSUE THREAD

**Issue by fuzzyers** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#38]
We need to be able to launch the games from the frontend otherwise it would be pointless having one.

**Comment by fuzzyers** [comment]
I have tried using a localfile execution system but it is no longer supported by current browsers.
This is likely no longer supported due to security concerns

**Comment by fuzzyers** [comment]
I am now trying out an api using child_process exec function

**Comment by SamanthaCra** [comment]
@fuzzyers Can you link this to a relevant branch or pull request please.

**Comment by fuzzyers** [comment]
Documentation In regards to the Game Execution can be found here

https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/wiki/Arcade-User-Interface-Backend-Documentation
https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/wiki/Frontend-Research
