### ISSUE TITLE
Final RFID Working

### ISSUE THREAD

**Issue by ramandeepkau** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#47]
This issue has been resolved and done with the basic RFID working with two led's RED and Green. The Green led will blink when you put a green card and the Red led will blink when you put a red card. The code can be found here: https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/pull/45

**Comment by ramandeepkau** [comment]
https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/assets/64877434/07ad0ba7-6662-4376-81ea-66410141f575

![WhatsApp Image 2024-04-09 at 2 07 36 PM](https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/assets/64877434/7902aec6-0625-4c32-9f06-d095f0698d73)

**Comment by OP-ReubenK** [comment]
this is related to issue #31

**Comment by ramandeepkau** [comment]
Uploading MicrosoftTeams-video.mp4…

**Comment by ramandeepkau** [comment]
That is the complete hardware of RFID
