### ISSUE TITLE
Create a "mood board" for controller holders

### ISSUE THREAD

**Issue by SamanthaCra** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#49]
This is to present to Grayson and decide on a final design.

From there we can see if we need to develop a model ourselves or if there is a suitable one accessible.

**Comment by SamanthaCra** [comment]
[Controllers Studio.pdf](https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/files/15123942/Controllers.Studio.pdf)

**Comment by SamanthaCra** [comment]
This presents a few options. 
- Creating controller holders that lets the controller chords be exposed. 
- Adding firm handles that can't be moved (not very enjoyable user experience) 
- Adding custom, flexible secure handles. 

Position on the machine is another factor to be considered. 
Storing the controllers in a draw/cupboard is another option.

**Comment by SamanthaCra** [comment]
https://imgur.com/a/q94KEdb A link to an idea for the third option.

**Comment by OP-ReubenK** [comment]
Here is a quick render for a possible simple controller arm. refining would need a clip to connect the actual controller and wire management.

![image](https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/assets/83677423/64710885-f19e-44d2-ac34-eea6eb341447)

![image](https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/assets/83677423/76adbd0a-f60c-4ae0-96bd-8bb04d206a98)

![image](https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/assets/83677423/dc861956-4d49-4834-b7ac-c1411b520226)

![image](https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/assets/83677423/7e860071-ebde-43b6-b760-59754764e073)

**Comment by Grayson-Orr** [comment]
I like this idea. I have concerns about printing this.

**Comment by SamanthaCra** [comment]
@Grayson-Orr Thanks for having a look, what in particular concerns you about printing this?

**Comment by SamanthaCra** [comment]
Concerns were about the state of 3D printers. This has generally been accepted as an idea. Will continue in a seperate issue.
