### ISSUE TITLE
Lock/Unlock Windows using RFID

### ISSUE THREAD

**Issue by ramandeepkau** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#60]
As a user, I want to be able to lock and unlock my Windows PC using my RFID tag, So that I can quickly gain access to my workstation securely.

**Comment by SamanthaCra** [comment]
Closing as this is a user story. Please refer to https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/wiki for where user stories go.

**Comment by SamanthaCra** [comment]
@ramandeepkau This still isn't an issue. Can you please open a separate issue to explain what needs done?

**Comment by ramandeepkau** [comment]
This issue has been split into different parts and milestones.
