### ISSUE TITLE
Finalise drawings for cabinet

### ISSUE THREAD

**Issue by SamanthaCra** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#69]
Suggestions
* Put the marquee back
* Possibly make the depth 600 instead of 500
* Angle up the controls to 10-15 degrees.

**Comment by fuzzyers** [comment]
[Arcade Machine v7 Drawing v3.pdf](https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/files/15371069/Arcade.Machine.v7.Drawing.v3.pdf)
