### ISSUE TITLE
Merge Staging into staging

### ISSUE THREAD

**Issue by kierenblack** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#92]
Can we merge Staging into staging and then delete Staging to avoid confusion

**Comment by kierenblack** [comment]
refer https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/pull/93

**Comment by OP-ReubenK** [comment]
this has been completed. "Staging" was renamed "XXStagingXX" rather than deleting it entirely
