### ISSUE TITLE
Windows PC Lock/Unlock Using RFID

### ISSUE THREAD

**Issue by ramandeepkau** [OtagoPolytechnic/third-year-studio-2024-rainy-arcade#96]
As a user, I want to use an RFID tag to lock and unlock my Windows PC, so that I can avoid the hassle of typing my password repeatedly throughout the day.

**Comment by SamanthaCra** [comment]
Closing as this is a user story. Please refer to the wiki for how to write issues correctly. https://github.com/OtagoPolytechnic/third-year-studio-2024-rainy-arcade/wiki
